server:
  port: 9096
  
spring:
  datasource:
    #schema: classpath*:db/schema.sql
    #data: classpath*:db/data.sql
    url: jdbc:postgresql://localhost:5432/wss
    username: wss_user
    password: wss_password
    initialization-mode: never
  

afisha:
  movies:
    baseUrl: "https://www.afisha.uz/afisha/movies/"
    skipMoviesCriteria: "на узбекском"
  baseUrl: "https://www.afisha.uz"