server:
  port: 9096

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    initialization-mode: never
    driver-class-name: org.postgresql.Driver
  liquibase:
    changeLog: classpath:db/db.changelog-master.yaml


afisha:
  movies:
    baseUrl: "https://www.afisha.uz/afisha/movies/"
    skipMoviesCriteria: "на узбекском"
    wrongLinkPart: "cinema"
  news:
    baseUrl: "https://www.gazeta.uz/ru/rss/?section=coronavirus"
  baseUrl: "https://www.afisha.uz"
  baseUrlGazeta: "https://www.gazeta.uz"
  scheduledTaskInitialDelay: "10000"
  scheduledTaskFixedDelay: "3600000"
  
coronavirus:
  globalStats:
    baseUrl: "https://www.worldometers.info/coronavirus/"
  scheduledTaskInitialDelay: "20000"
  scheduledTaskFixedDelay: "600000"