server:
  port: 9096
  
# JPA and datasource
spring:
#  jpa:
#    hibernate:
#      ddl-auto: none # for schema creation
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        jdbc:
#          lob:
#            non_contextual_creation: true # to avoid Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented
  datasource:
    schema: classpath*:db/schema.sql
    #data: classpath*:db/data.sql
    url: jdbc:postgresql://localhost:5432/wss
    username: wss_user
    password: wss_password
    initialization-mode: always
  

afisha:
  movies:
    baseUrl: "https://www.afisha.uz/afisha/movies/"
    skipMoviesCriteria: "на узбекском"
  baseUrl: "https://www.afisha.uz"