package com.wictorlyan.webscraperservice.property

const val TABLE_AFISHA_CINEMA = "afisha_cinemas"
const val TABLE_AFISHA_MOVIE = "afisha_movies"
const val TABLE_AFISHA_CINEMA_MOVIE = "afisha_cinemas_movies"

const val TABLE_CORONA_COUNTRY_STATS = "corona_country_stats"

const val COLUMN_ID = "id"
const val COLUMN_NAME = "name"
const val COLUMN_LINK_AFISHA = "link_afisha"
const val COLUMN_LINK_ABOUT = "link_about"
const val COLUMN_CREATED_DATE = "created_date"
const val COLUMN_MODIFIED_DATE = "modified_date"
const val COLUMN_GENRE = "genre"
const val COLUMN_LINK = "link"
const val COLUMN_CINEMA_ID = "cinema_id"
const val COLUMN_CINEMA_NAME = "cinema_name"
const val COLUMN_MOVIE_ID = "movie_id"
const val COLUMN_MOVIE_NAME = "movie_name"
const val COLUMN_MOVIE_DATE = "movie_date"
const val COLUMN_MOVIE_TIME = "movie_time"
const val COLUMN_FORMAT = "format"
const val COLUMN_IMAGE = "image"

const val COLUMN_COUNTRY = "country"
const val COLUMN_TOTAL_CASES = "total_cases"
const val COLUMN_NEW_CASES = "new_cases"
const val COLUMN_TOTAL_DEATHS = "total_deaths"
const val COLUMN_NEW_DEATHS = "new_deaths"
const val COLUMN_TOTAL_RECOVERED = "total_recovered"
const val COLUMN_ACTIVE_CASES = "active_cases"
const val COLUMN_SERIOUS_CASES = "serious_cases"
const val COLUMN_TOTAL_CASES_BY_MILLION = "total_cases_by_million"
const val COLUMN_DEATHS_BY_MILLION = "deaths_by_million"
const val COLUMN_FIRST_CASE_DATE = "first_case_date"
